python train.py --experiment dkvb_resnet50_512_pretrain
python train.py --experiment vq_resnet50_512_pretrain
python train.py --experiment dkvb_resnet50_128_pretrain
python train.py --experiment vq_resnet50_128_pretrain
python train.py --experiment dkvb_resnet50_64_pretrain
python train.py --experiment vq_resnet50_64_pretrain
python train.py --experiment dkvb_resnet50_1_pretrain
python train.py --experiment vq_resnet50_1_pretrain
python train.py --experiment baseline_resnet50_pretrain